import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import {
  profile,
  deliveryCompetencies,
  leadershipCompetencies,
  experience,
  highlights,
  methodologies,
  tools,
  education,
} from "@/lib/resume-data";

export const runtime = "nodejs";
export const maxDuration = 60;

/* Light-theme palette (no dark backgrounds) */
const TEAL: [number, number, number] = [13, 138, 131];
const TEAL_SOFT: [number, number, number] = [232, 244, 243];
const AMBER: [number, number, number] = [217, 146, 25];
const INK: [number, number, number] = [42, 48, 47];
const MUTED: [number, number, number] = [92, 102, 100];

/* Resume data is static — cache the generated bytes per process
   so repeat downloads skip the full generation pass. */
let cachedPdf: ArrayBuffer | null = null;

export async function GET() {
  if (cachedPdf) {
    return new NextResponse(cachedPdf, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'inline; filename="Karthik-Easam-Project-Manager-Resume.pdf"',
        "Cache-Control": "public, max-age=3600",
        "X-PDF-Cache": "HIT",
      },
    });
  }
  const doc = new jsPDF({ unit: "pt", format: "a4", compress: true });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 52; // page margin
  const CW = W - M * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > H - 56) {
      doc.addPage();
      y = 64;
      return true;
    }
    return false;
  };

  const setFont = (style: "normal" | "bold" | "italic", size: number) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
  };

  const bulletList = (items: string[], opts?: { indent?: number; size?: number }) => {
    const size = opts?.size ?? 9.5;
    const indent = opts?.indent ?? 12;
    setFont("normal", size);
    doc.setTextColor(...INK);
    for (const item of items) {
      const lines = doc.splitTextToSize(item, CW - indent - 14) as string[];
      ensureSpace(lines.length * (size + 3.4) + 4);
      doc.setFillColor(...TEAL);
      doc.circle(M + indent + 2, y + size * 0.42, 1.6, "F");
      doc.text(lines, M + indent + 10, y + size);
      y += lines.length * (size + 3.4) + 3.5;
    }
  };

  const sectionTitle = (title: string) => {
    ensureSpace(46);
    y += 10;
    setFont("bold", 11.5);
    doc.setTextColor(...TEAL);
    doc.text(title.toUpperCase(), M, y);
    const tw = doc.getTextWidth(title.toUpperCase());
    doc.setFillColor(...TEAL);
    doc.rect(M, y + 5, tw, 1.6, "F");
    doc.setFillColor(...AMBER);
    doc.rect(M + tw + 3, y + 5, 14, 1.6, "F");
    y += 18;
  };

  /* ---------- header band (light teal tint, NOT dark) ---------- */
  doc.setFillColor(...TEAL_SOFT);
  doc.rect(0, 0, W, 118, "F");
  doc.setFillColor(...TEAL);
  doc.rect(0, 118, W, 3, "F");

  setFont("bold", 26);
  doc.setTextColor(...TEAL);
  doc.text(profile.name.toUpperCase(), M, 52);

  setFont("bold", 11);
  doc.setTextColor(...AMBER);
  doc.text(
    "Project Manager  ·  Software Delivery  ·  Agile/Scrum  ·  Stakeholder & Risk Management",
    M,
    71
  );

  setFont("normal", 9.5);
  doc.setTextColor(...MUTED);
  doc.text(
    `${profile.location}   |   ${profile.phone}   |   ${profile.email}   |   ${profile.linkedin}`,
    M,
    90
  );
  y = 146;

  /* ---------- summary ---------- */
  sectionTitle("Professional Summary");
  setFont("normal", 9.8);
  doc.setTextColor(...INK);
  const summary = [
    profile.summaryIntro,
    profile.summaryBody,
    profile.summaryProof,
  ].join(" ");
  const sumLines = doc.splitTextToSize(summary, CW) as string[];
  doc.text(sumLines, M, y);
  y += sumLines.length * 13.4;

  /* ---------- competencies (two columns) ---------- */
  sectionTitle("Core Competencies");
  const colW = (CW - 24) / 2;
  const renderCompColumn = (title: string, items: string[], x: number) => {
    setFont("bold", 9.5);
    doc.setTextColor(...TEAL);
    doc.text(title, x, y);
    let cy = y + 13;
    setFont("normal", 9);
    doc.setTextColor(...INK);
    for (const c of items) {
      const lines = doc.splitTextToSize(`• ${c}`, colW) as string[];
      doc.text(lines, x, cy);
      cy += lines.length * 11.6;
    }
    return cy;
  };
  const leftEnd = renderCompColumn("Project & Delivery Management", deliveryCompetencies, M);
  const rightEnd = renderCompColumn("Stakeholder & Team Leadership", leadershipCompetencies, M + colW + 24);
  y = Math.max(leftEnd, rightEnd) + 4;

  /* ---------- experience ---------- */
  sectionTitle("Professional Experience");
  for (const job of experience) {
    ensureSpace(84);
    setFont("bold", 11);
    doc.setTextColor(...TEAL);
    doc.text(job.role, M, y);
    setFont("bold", 9.5);
    doc.setTextColor(...AMBER);
    doc.text(job.period, W - M - doc.getTextWidth(job.period), y);
    y += 13;
    setFont("bold", 9.8);
    doc.setTextColor(...INK);
    doc.text(`${job.company} — ${job.location}`, M, y);
    y += 13;

    bulletList(
      job.points.map((p) => p.text),
      { size: 9.5 }
    );

    for (const sp of job.subProjects ?? []) {
      ensureSpace(70);
      // soft tinted sub-card
      const subLines: string[][] = [];
      setFont("normal", 9.3);
      for (const p of sp.points) {
        subLines.push(doc.splitTextToSize(p, CW - 26) as string[]);
      }
      const descLines = doc.splitTextToSize(sp.description, CW - 26) as string[];
      const blockH =
        30 + descLines.length * 11.8 + subLines.reduce((a, lines) => a + lines.length * 11.6 + 2, 0) + 10;
      ensureSpace(blockH);
      doc.setFillColor(246, 251, 250);
      const boxTop = y - 6;
      doc.roundedRect(M, boxTop, CW, blockH, 6, 6, "F");
      doc.setFillColor(...TEAL);
      doc.rect(M, boxTop, 3, blockH, "F");

      y += 6;
      setFont("bold", 10);
      doc.setTextColor(...TEAL);
      doc.text(sp.name, M + 14, y);
      setFont("italic", 8.8);
      doc.setTextColor(...AMBER);
      doc.text(sp.tagline, M + 14, y + 11);
      y += 24;

      setFont("normal", 9.3);
      doc.setTextColor(...INK);
      doc.text(descLines, M + 14, y);
      y += descLines.length * 11.8 + 4;

      setFont("normal", 9.2);
      for (const p of sp.points) {
        const lines = doc.splitTextToSize(p, CW - 26) as string[];
        doc.setFillColor(...AMBER);
        doc.circle(M + 16, y + 3, 1.3, "F");
        doc.text(lines, M + 24, y + 3.4);
        y += lines.length * 11.6 + 2;
      }
      y += 8;
    }
    y += 6;
  }

  /* ---------- highlights ---------- */
  sectionTitle("Key Highlights");
  bulletList(
    highlights.map((h) => `${h.title} — ${h.description}`),
    { size: 9.5 }
  );

  /* ---------- methodologies & tools ---------- */
  sectionTitle("Methodologies & Tools");
  setFont("bold", 9.5);
  doc.setTextColor(...INK);
  doc.text("Methodologies: ", M, y);
  const mLabelW = doc.getTextWidth("Methodologies: ");
  setFont("normal", 9.5);
  doc.setTextColor(...MUTED);
  const mLines = doc.splitTextToSize(methodologies.join(" · "), CW - mLabelW) as string[];
  doc.text(mLines, M + mLabelW, y);
  y += mLines.length * 12.6 + 4;

  setFont("bold", 9.5);
  doc.setTextColor(...INK);
  doc.text("Tools & Platforms: ", M, y);
  const tLabelW = doc.getTextWidth("Tools & Platforms: ");
  setFont("normal", 9.5);
  doc.setTextColor(...MUTED);
  const tLines = doc.splitTextToSize(tools.join(" · "), CW - tLabelW) as string[];
  doc.text(tLines, M + tLabelW, y);
  y += tLines.length * 12.6;

  /* ---------- education ---------- */
  sectionTitle("Education");
  setFont("bold", 10);
  doc.setTextColor(...INK);
  doc.text(education.degree, M, y);
  y += 13;
  setFont("normal", 9.5);
  doc.setTextColor(...MUTED);
  doc.text(`${education.school}  ·  ${education.period}`, M, y);

  /* ---------- footer on every page ---------- */
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    setFont("normal", 8);
    doc.setTextColor(...MUTED);
    doc.text(
      `${profile.name} — Project Manager  ·  ${profile.email}  ·  ${profile.phone}`,
      M,
      H - 26
    );
    doc.text(`Page ${i} of ${pages}`, W - M - 46, H - 26);
  }

  const pdfBytes = doc.output("arraybuffer");
  cachedPdf = pdfBytes as ArrayBuffer;

  return new NextResponse(pdfBytes as ArrayBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'inline; filename="Karthik-Easam-Project-Manager-Resume.pdf"',
      "Cache-Control": "public, max-age=3600",
      "X-PDF-Cache": "MISS",
    },
  });
}
